"""Create detections table

Revision ID: ef4ff93a10b1
Revises: 
Create Date: 2023-04-09 02:17:53.701662

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ef4ff93a10b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('top_left_x', sa.Integer(), nullable=True),
                    sa.Column('top_left_y', sa.Integer(), nullable=True),
                    sa.Column('width', sa.Integer(), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('confidence', sa.Float(), nullable=True),
                    sa.Column('label', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('detections')
    # ### end Alembic commands ###
